config/routes.rb
Applistaff::Application.routes.draw do
  get "password_resets/new"

  get "sessions/new"

  get "about/index"
  get "about/index"
  get "home/index"
  get "dispos/index"
  get "users/edit"
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "saisie" => "dispos#new", :as => "saisie"
  get "myself" => "dispos#index", :as => "myself"
  
  resources :about

  resources :statuts

  resources :dispos

  resources :users
  
  resources :sessions
  
  resources :about
  
  resources :password_resets

   root :to => 'home#index'

end

app/models/statut.rb
class Statut < ActiveRecord::Base
  attr_accessible :intitule
  has_many :dispos
  has_many :users, :through => :dispos
  
  validates_presence_of :intitule, :message => "Il faut un nom !"
end

app/controllers/statuts_controller.rb
class StatutsController < ApplicationController
  # GET /statuts
  # GET /statuts.json
  def index
    @statuts = Statut.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @statuts }
    end
  end

  # GET /statuts/1
  # GET /statuts/1.json
  def show
    @statut = Statut.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @statut }
    end
  end

  # GET /statuts/new
  # GET /statuts/new.json
  def new
    @statut = Statut.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @statut }
    end
  end

  # GET /statuts/1/edit
  def edit
    @statut = Statut.find(params[:id])
  end

  # POST /statuts
  # POST /statuts.json
  def create
    @statut = Statut.new(params[:statut])

    respond_to do |format|
      if @statut.save
        format.html { redirect_to @statut, :notice => 'Statut was successfully created.' }
        format.json { render :json => @statut, :status => :created, :location => @statut }
      else
        format.html { render :action => "new" }
        format.json { render :json => @statut.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /statuts/1
  # PUT /statuts/1.json
  def update
    @statut = Statut.find(params[:id])

    respond_to do |format|
      if @statut.update_attributes(params[:statut])
        format.html { redirect_to @statut, :notice => 'Statut was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @statut.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /statuts/1
  # DELETE /statuts/1.json
  def destroy
    @statut = Statut.find(params[:id])
    @statut.destroy

    respond_to do |format|
      format.html { redirect_to statuts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statuts_helper.rb
module StatutsHelper
end

app/views/statuts/_form.html.erb
<%= form_for(@statut) do |f| %>
  <% if @statut.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statut.errors.count, "error") %> prohibited this statut from being saved:</h2>

      <ul>
      <% @statut.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :intitule %><br />
    <%= f.text_field :intitule %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuts/edit.html.erb
<h1>Editing statut</h1>

<%= render 'form' %>

<%= link_to 'Show', @statut %> |
<%= link_to 'Back', statuts_path %>

app/views/statuts/index.html.erb
<h1>Listing statuts</h1>

<table>
  <tr>
    <th>Intitule</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuts.each do |statut| %>
  <tr>
    <td><%= statut.intitule %></td>
    <td><%= link_to 'Show', statut %></td>
    <td><%= link_to 'Edit', edit_statut_path(statut) %></td>
    <td><%= link_to 'Destroy', statut, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />



<%= link_to 'New Statut', new_statut_path %>

app/views/statuts/new.html.erb
<h1>New statut</h1>

<%= render 'form' %>

<%= link_to 'Back', statuts_path %>

app/views/statuts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Intitule:</b>
  <%= @statut.intitule %>
</p>


<%= link_to 'Edit', edit_statut_path(@statut) %> |
<%= link_to 'Back', statuts_path %>