config/routes.rb
Applistaff::Application.routes.draw do
  get "password_resets/new"

  get "sessions/new"

  get "about/index"
  get "about/index"
  get "home/index"
  get "dispos/index"
  get "users/edit"
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "saisie" => "dispos#new", :as => "saisie"
  get "myself" => "dispos#index", :as => "myself"
  
  resources :about

  resources :statuts

  resources :dispos

  resources :users
  
  resources :sessions
  
  resources :about
  
  resources :password_resets

   root :to => 'home#index'

end

app/models/dispo.rb
class Dispo < ActiveRecord::Base
  attr_accessible :jour, :statut_id, :user_id, :comments
  belongs_to :user
  belongs_to :statut
  
  validates_presence_of :statut_id, :message => "Merci de saisir une dispo !"

  
  scope :of_day, lambda { |day| where(:jour => day.beginning_of_day..day.end_of_day) }
end

app/controllers/dispos_controller.rb
class DisposController < ApplicationController
  # GET /dispos
  # GET /dispos.json
  def index
    
    @dispos = Dispo.where("user_id = ?", current_user)
    @date = params[:day] ? Date.parse(params[:day]) : Time.now.in_time_zone('Paris').to_date
    @monthly = params[:month] ? Date.parse(params[:month]) : Time.now.in_time_zone('Paris').to_date
    @statuts = Statut.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @dispos }
    end
  end

  # GET /dispos/1
  # GET /dispos/1.json
  def show
    @dispo = Dispo.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @dispo }
    end
  end

  # GET /dispos/new
  # GET /dispos/new.json
  def new
    @dispo = Dispo.new
    if params[:day]
      @dispo.jour = params[:day]
    else
      @dispo.jour = Time.current().in_time_zone('Paris')
    end
    
    @dispos = Array.new(3) { @current_user.dispo.build }
    
    @statuts = Statut.all
    @date = params[:day] ? Date.parse(params[:day]) : Time.current().in_time_zone('Paris')

    respond_to do |format|
#     if @dispo.jour.wday == 6 
#        format.html { redirect_to new_dispo_path(:day => @dispo.jour.to_date+2) }
 #       format.json { render :json => @dispo, :status => :created, :location => @dispo }
#     else      
      format.html # new.html.erb
      format.json { render :json => @dispo }
#    end
  end
  end

  # GET /dispos/1/edit
  def edit
    @dispo = Dispo.find(params[:id])
  end

  # POST /dispos
  # POST /dispos.json
  def create
    
    @date = params[:day] ? Date.parse(params[:day]) : Date.current()
    
    @dispo = Dispo.new(params[:dispo])
    @statuts = Statut.all
    
    respond_to do |format|
      if @dispo.save
        flash[:notice] = "OK !"
        format.html { redirect_to new_dispo_path(:day => @dispo.jour.tomorrow.to_date) }
        format.json { render :json => @dispo, :status => :created, :location => @dispo }
        
      else
        flash[:error] = "Merci de verifier votre formulaire."
        format.html { redirect_to new_dispo_path(:day => @dispo.jour.to_date) }
        format.json { render :json => @dispo.errors, :status => :unprocessable_entity }
      end
      
    end
  end

  # PUT /dispos/1
  # PUT /dispos/1.json
  def update
    @dispo = Dispo.find(params[:id])

    respond_to do |format|
      if @dispo.update_attributes(params[:dispo])
        format.html { redirect_to @dispo, :notice => 'Dispo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @dispo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dispos/1
  # DELETE /dispos/1.json
  def destroy
    @dispo = Dispo.find(params[:id])
    @dispo.destroy
    flash[:notice] = "Supprimee!"
    respond_to do |format|
      format.html { redirect_to new_dispo_path(:day => @dispo.jour.to_date) }
      format.json { head :no_content }
    end
  end
end

app/helpers/dispos_helper.rb
module DisposHelper
end

app/views/dispos/_form.html.erb
<% ajd = @dispo.jour%>
<% if @dispo.jour.wday == 6 %>
<div class="alert alert-info">
	Attention, le <%= ajd.to_date.to_s(:short)  %>, c'est un samedi ! <%= link_to 'Passer directement au lundi en cliquant ici', new_dispo_path(:day => @dispo.jour.to_date+2) %>
	</div>
<% end %>
<% if @dispo.jour.wday == 0 %>
<div class="alert alert-info">
	Attention, le <%= ajd.to_date.to_s(:short) %>, c'est un dimanche ! <%= link_to 'Passer directement au lundi en cliquant ici', new_dispo_path(:day => @dispo.jour.to_date+1) %>
	</div>
<% end %>

<% if current_user.dispos.of_day(@date).any? %>
	<div id="deja_dispo" class="well">
		Le <%= ajd.to_time.strftime("%a %d %b") %>, tu es : 
		<% current_user.dispos.of_day(@date).each do |truc| %>
		 	<span class="label label-info"><%= truc.statut.intitule %></span>
			 <% if truc.comments? %>
			- <i>"<%= truc.comments %>"</i>
			<% end %>
			<br /><br />
				<div id="proposer_modifier" class="controls">
					<%= link_to dispo_path(truc.id ), options = { :confirm => 'Supprimer cette valeur ?', :method => :delete, :class => "btn btn-danger btn-small",  } do %>
					Supprimer cette valeur
					<i class="icon-trash"></i>
					<% end %>
					<br /><br />
				</div>
				<div id="next_days" class="btn-group">
					<%= link_to '«', new_dispo_path(:day => @dispo.jour.yesterday.to_date), :class => "btn" %>
					<button class="btn"><%= ajd.to_time.strftime("%a %d %b") %></button>
					<%= link_to '»' , new_dispo_path(:day => @dispo.jour.tomorrow.to_date), :class => "btn" %>
				</div>
		<% end %>
	</div>	
	
<% else %>
	<%= form_for(@dispo, :html => { :class => "well" } ) do |f| %>
	  <% if @dispo.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@dispo.errors.count, "error") %> prohibited this dispo from being saved:</h2>

	      <ul>
	      <% @dispo.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	 	<fieldset>
			<%= f.hidden_field :user_id, :value => current_user.id %>
	  	<div>
		<%= f.hidden_field :jour %>
	  </div>
	   <div class="control-group">
		<label class="control-label"><%= current_user.prenom %>, le <%= ajd.to_time.strftime("%A %d %b")  %>, tu es :</label>
			<div class="controls">
				<% @statuts.each do |statut| %>
				<label class="radio">	
						<%= f.radio_button :statut_id, statut.id %> <%= statut.intitule %>	
					</label>
				<% end %>	
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<label class="control-label" for="textarea">Infos complémentaires (projet ...) :</label>
					<%= f.text_area :comments, :rows => 2, :class => "input-xlarge" %>
			</div>
		</div>
	  <div class="controls">
	    <%= f.submit 'Enregistrer et passer au jour suivant', :class => "btn btn-success" %>
	  </div>
	 </fieldset>
	</div>
	<div>
		<div id="next_days" class="btn-group">
			<%= link_to '«', new_dispo_path(:day => @dispo.jour.yesterday.to_date), :class => "btn" %>
			<button class="btn"><%= ajd.to_time.strftime("%a %d %b") %></button>
			<%= link_to '»' , new_dispo_path(:day => @dispo.jour.tomorrow.to_date), :class => "btn" %>
		</div>
	<% end %>
<% end %>

app/views/dispos/edit.html.erb
<h1>Editing dispo</h1>

<%= render 'form' %>

<%= link_to 'Show', @dispo %> |
<%= link_to 'Back', dispos_path %>

app/views/dispos/index.html.erb
<div id="calendar">
  <h2 id="month">
    <%= link_to "<", :day => (@date.beginning_of_month-1) %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to ">", :day => (@date.end_of_month+1) %>
  </h2>
  <%= calendar_for @dispos, :year => @date.year, :month => @date.month do |calendar| %>
    <%= calendar.head('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi') %>
    <%= calendar.day(:day_method => :jour) do |date, dispos| %>
      <%= date.day %>
      <ul>
        <% for dispo in dispos %>	
			<% if dispo.statut.id == 1 %>
          		<li><span class="label label-success"><%= dispo.statut.intitule %></span>
      				<%= link_to '/myself', options = { :confirm => 'Supprimer cette valeur ?', :method => :delete, :title => "Supprimer cette valeur", :rel => "tooltip"} do %>
					<i class="icon-remove" title="Supprimer cette valeur"></i>
					<% end %>
				</li>
				<li>
					<%= dispo.comments %>
				</li>
			<% end %>
			
			<% if dispo.statut.id == Statut.first.id+1 %>
          		<li><span class="label label-important">Dispo</span>
      				<%= link_to dispo, options = { :confirm => 'Supprimer cette valeur ?', :method => :delete }, html_options = { :title => "Supprimer cette valeur", :rel => "tooltip"} do %>
				<i class="icon-remove" title="Supprimer cette valeur"></i>
					<% end %>
				</li>
				<li>
					<%= dispo.comments %>
				</li>
			<% end %>
			
			<% if dispo.statut.id == Statut.first.id+2 %>
          		<li><span class="label label-warning">Ne sait pas</span>			
	      			<%= link_to dispo, options = { :confirm => 'Supprimer cette valeur ?', :method => :delete }, html_options = { :title => "Supprimer cette valeur", :rel => "tooltip"} do %>
					<i class="icon-remove" title="Supprimer cette valeur"></i>
					<% end %>
				</li>
				<li>
					<%= dispo.comments %>
				</li>
			<% end %>

			<% if dispo.statut.id == Statut.first.id+3 %>
          		<li><span class="label">Malade</span>			
	      			<%= link_to dispo, options = { :confirm => 'Supprimer cette valeur ?', :method => :delete }, html_options = { :title => "Supprimer cette valeur", :rel => "tooltip"} do %>
					<i class="icon-remove" title="Supprimer cette valeur"></i>
					<% end %>
				</li>
				<li>
					<%= dispo.comments %>
				</li>
			<% end %>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>
<br />

<%= link_to 'New Dispo', new_dispo_path %>

app/views/dispos/new.html.erb
<%= render 'form' %>

app/views/dispos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Jour:</b>
  <%= @dispo.jour %>
</p>

<p>
  <b>Statut:</b>
  <%= @dispo.statut_id %>
</p>

<p>
  <b>User:</b>
  <%= @dispo.user_id %>
</p>


<%= link_to 'Edit', edit_dispo_path(@dispo) %> |
<%= link_to 'Back', dispos_path %>