config/routes.rb
Applistaff::Application.routes.draw do
  get "password_resets/new"

  get "sessions/new"

  get "about/index"
  get "about/index"
  get "home/index"
  get "dispos/index"
  get "users/edit"
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "saisie" => "dispos#new", :as => "saisie"
  get "myself" => "dispos#index", :as => "myself"
  
  resources :about

  resources :statuts

  resources :dispos

  resources :users
  
  resources :sessions
  
  resources :about
  
  resources :password_resets

   root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStaffing</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				 <%= link_to "MyStaffing", root_path, :class => "brand" %>
				<div class="nav-collapse">
		   			<ul class="nav">
		    			<li><a href="/dispos/new">Saisir</a></li>
						<li><a href="/myself/">Synthèse</a></li>
		    			<li><a href="/users/">Tableau de bord</a></li>
		 				<li class="divider-vertical"></li>
		    		</ul>
				</div>
				 <% if current_user %>
				<div class="nav-collapse">
				<div class="pull-right">
					<a class="btn btn-small" href="<%= edit_user_path(current_user) %>">
						<i class="icon-user icon-white"/> <%= current_user.prenom %> <%= current_user.nom %></i>
					</a>
					<a class="btn btn-danger btn-small" href="/log_out">
						<i class="icon-off icon-white"></i>
					</a>
				</div>
				</div>
				
				<% else %>
				<div class="nav-collapse">
				<div class="pull-right">
					<a class="btn btn-success btn-medium" href="/log_in">
						Connexion <i class="icon-user icon-white"></i>
					</a>
				</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="container">
		<div id="user_nav">
			<% flash.each do |name, msg| %>
			<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
			
			  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
			<% end %>	
		  <% if current_user %>	
			<%= yield %>
		  <% else %>
			<%= yield %>
	      	<%= link_to "Se connecter", log_in_path %> ou	<%= link_to "s'inscrire", sign_up_path %>	
		  <% end %>
		</div>
		<hr />
<footer>
	© 2012 - <%= link_to 'MyStaffing', 'http://www.edouardschlumberger.com', :target => '_blank' %> - MyStaffing est en version Alpha. Attention aux bugs ;-)
	</footer>
	</div>
	
</body>
</html>